spring:
  application:
    name: my-chat-api
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/chat}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://root:admin@localhost:27017/chat?authSource=admin}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8080}
  address: 0.0.0.0
  servlet:
    context-path: /api

cors:
  allowed-origins: ${CORS_ORIGIN:http://localhost:8000}
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"

security:
  jwt:
    secret-key: ${JWT_SECRET:QxbLLjUM1t+RusKI1krTor2PWEat4nOCZeRkL1auXJU=}
    expiration-time: ${EXPIRATION:900000}
  

